### ISSUE TITLE
Запрос разрешения на использование сайта

### ISSUE THREAD

**Issue by Finbrand** [infoculture/plainrussian#6]
Добрый день. 
Можно ли использованию API и cайт в школьном проекте по информатике а лицее ВШЭ? 
детали проекта - в https://github.com/Finbrand/project1

**Comment by ivbeg** [comment]
Добрый день. Да, конечно. API и сайт опубликованы под свободными лицензиями, Вы имеете право использовать их по своему усмотрению.
